# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


10.times do |cpt|
  char = Character.create!(
    profile_pic: File.open("#{Rails.root.to_s}/app/assets/images/icons/#{cpt}.png")
  )
  char.random_spend_caracs_points
end

[
  {
    name: "Doran's Blade",
    type: "Weapon",
    description: Faker::Lorem.sentence,
    lvl: 1,
    price: 10,
    given_speed: -1,
    given_strength: 3,
    max_capacity: 15,
    power: 3
  },
  {
    name: "Edge of Eternity",
    type: "Weapon",
    description: Faker::Lorem.sentence ,
    lvl: 2,
    price: 20,
    given_speed: 2,
    given_strength: 2,
    given_agility: 2,
    power: 2,
    given_max_hp: 10,
    max_capacity: 25,
  },
  {
    name: "Armageddon",
    type: "Weapon",
    description: Faker::Lorem.sentence ,
    lvl: 3,
    price: 120,
    given_speed: -5,
    given_strength: 5,
    given_agility: -2,
    power: 10,
    given_max_hp: -10,
    max_capacity: 10,
  },
  {
    name: "Peacemaker",
    type: "Weapon",
    description: Faker::Lorem.sentence ,
    lvl: 4,
    price: 200,
    given_speed: 4,
    given_strength: 0,
    given_agility: 2,
    power: 1,
    given_max_hp: 100,
    max_capacity: 25,
  },
  {
    name: "Frost Cleaver",
    type: "Weapon",
    description: Faker::Lorem.sentence ,
    lvl: 5,
    price: 550,
    given_speed: 10,
    given_strength: -5,
    given_agility: 12,
    power: 10,
    given_max_hp: 0,
    max_capacity: 25,
  },
  {
    name: "Flimsy Cleaver",
    type: "Weapon",
    description: Faker::Lorem.sentence ,
    lvl: 6,
    price: 1000,
    given_speed: 10,
    given_strength: 5,
    given_agility: 15,
    power: 15,
    given_max_hp: 20,
    max_capacity: 5,

  },
  {
    name: "Headcover of Condemned Visions",
    type: "Helmet",
    description: Faker::Lorem.sentence,
    lvl: 1,
    price: 10,
    given_speed: 2,
    max_capacity: 10,
  },
  {
    name: "Faceguard of Immortal Nights",
    type: "Helmet",
    description: Faker::Lorem.sentence,
    lvl: 2,
    price: 100,
    given_speed: -1,
    given_strength: 2,
    max_capacity: 20,
  },
  {
    name: "Adamantite Helmet of Timeless Misery",
    type: "Helmet",
    description: Faker::Lorem.sentence,
    lvl: 3,
    price: 350,
    given_speed: 10,
    given_strength: 0,
    given_agility: 4,
    max_capacity: 10,
  },
  {
    name: "Skeletal Crown of Unholy Trials",
    type: "Helmet",
    description: Faker::Lorem.sentence,
    lvl: 4,
    price: 500,
    given_speed: -5,
    given_strength: 10,
    given_agility: 4,
    max_capacity: 30,
  },
  {
    name: "Crazed Golden Casque",
    type: "Helmet",
    description: Faker::Lorem.sentence,
    lvl: 5,
    price: 1000,
    max_capacity: 100,
  },
  {
    name: "Chestpiece of Binding Nights",
    type: "Chest",
    description: Faker::Lorem.sentence,
    lvl: 1,
    price: 20,
    given_speed: 1,
    given_strength: 1,
    given_agility: 1,
    given_max_hp: 10,
    max_capacity: 20,
  },
  {
    name: "Chestpiece of Infernal Voices",
    type: "Chest",
    description: Faker::Lorem.sentence,
    lvl: 2,
    price: 200,
    given_agility: -2,
    given_speed: -2,
    given_strength: 15,
    given_max_hp: 10,
    max_capacity: 100,
  },
  {
    name: "Bronzed Batteplate of Infernal Freedom",
    type: "Chest",
    description: Faker::Lorem.sentence,
    lvl: 3,
    price: 500,
    given_max_hp: 20,
    given_strength: 20,
    max_capacity: 5,
  },
  {
    name: "Obsidian Batteplate of Lost Whispers",
    type: "Chest",
    description: Faker::Lorem.sentence,
    lvl: 4,
    price: 800,
    given_agility: 10,
    given_max_hp: 50,
    given_speed: 10,
    given_strength: -10,
    max_capacity: 20,
  },
  {
    name: "Omega",
    type: "Shield",
    description: Faker::Lorem.sentence,
    lvl: 1,
    price: 20,
    max_capacity: 10
  },
  {
    name: "Cataclysm",
    type: "Shield",
    description: Faker::Lorem.sentence,
    lvl: 2,
    price: 100,
    max_capacity: 10,
    given_agility: 10,
    given_max_hp: -10
  },
  {
    name: "Voice of Madness",
    type: "Shield",
    description: Faker::Lorem.sentence,
    lvl: 3,
    price: 300,
    given_speed: -10,
    given_strength: 20,
    max_capacity: 20
  },
  {
    name: "Loyal Blockade",
    type: "Shield",
    description: Faker::Lorem.sentence,
    lvl: 4,
    price: 1000,
    given_agility: 2,
    given_speed: -2,
    given_strength: 2,
    max_capacity: 50,
  },
  {
    name: "Greaves of Haunted Glory",
    type: "Boot",
    description: Faker::Lorem.sentence,
    lvl: 1,
    price: 10,
    given_speed: 5,
    max_capacity: 10
  },
  {
    name: "Spurs of Lost Fires",
    type: "Boot",
    description: Faker::Lorem.sentence,
    lvl: 2,
    price: 200,
    given_speed: 20,
    max_capacity: 5,
    given_max_hp: -5,
  },
  {
    name: "Ebon Boots of Fallen Lands",
    type: "Boot",
    description: Faker::Lorem.sentence,
    lvl: 3,
    price: 400,
    given_speed: 8,
    given_strength: 10,
    max_capacity: 20,
  },
  {
    name: "Bronzed Footguards of Condemned Honor",
    type: "Boot",
    description: Faker::Lorem.sentence,
    lvl: 4,
    price: 500,
    given_speed: 5,
    given_max_hp: 50,
    max_capacity: 20,
  },
].each do |gear_params|
  Gear.create!(gear_params)
end
